#!/bin/sh
ssh root@175.106.99.197 <<EOF
    cd ~/home/node_image
    git pull origin main
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 16.4.0
    npm install
    npm install -g pm2
    pm2 restart ecosystem.config.js
    exit
EOF
